[package]
name = "iff"
version = "0.1.0"
authors = ["Utkarsh Kukreti <utkarshkukreti@gmail.com>"]
edition = "2018"
description = "A macro for if / if let chains until [RFC 2497] is implemented."
repository = "https://github.com/utkarshkukreti/iff.rs"
license = "MIT/Apache-2.0"

[dependencies]
